/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import model.*;
import controller.taskManager;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import storage.DatabaseManager;



/**
 *
 * @author Dottedsocks
 */
public class mainWindow extends javax.swing.JFrame {
    //mogulega otharfi, thar sem thetta er ekki birt strax? 
    Flight searchFlights;
    Booking BookedFlight;
    Passenger PassengerFlight;
    //public int Adgerd;
    taskManager JoeTheTaskManager;
    
    
    
    /**
     * Creates new form leitargluggi
     */
    public mainWindow() {
        initComponents();
        
        searchFlights = new Flight();
        BookedFlight = new Booking();
        PassengerFlight = new Passenger();
        //Adgerd = 1;
        JoeTheTaskManager = new taskManager();
        jResultPanel.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLeitarPanel = new javax.swing.JPanel();
        jToWhere = new javax.swing.JComboBox<>();
        jFromWhere = new javax.swing.JComboBox<>();
        jAmount = new javax.swing.JComboBox<>();
        searchButton = new javax.swing.JButton();
        jWhen = new javax.swing.JTextField();
        jResultPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResults = new javax.swing.JTable();
        jBacktoSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLeitarPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLeitarPanelComponentHidden(evt);
            }
        });

        jToWhere.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose destination", "Akureyri", "Reykjavík", "Egilstaðir", "Ísafjörður", "Höfn í Hornafirði", " " }));
        jToWhere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToWhereActionPerformed(evt);
            }
        });

        jFromWhere.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Veldu brotfarastað", "Akureyri", "Reykjavík", "Egilsstaðir", "Hólmavík", "Höfn í Hornafirði", "Ísafjörður" }));
        jFromWhere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFromWhereActionPerformed(evt);
            }
        });

        jAmount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fjöldi", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jWhen.setText("dd/mm/yyyy");
        jWhen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWhenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLeitarPanelLayout = new javax.swing.GroupLayout(jLeitarPanel);
        jLeitarPanel.setLayout(jLeitarPanelLayout);
        jLeitarPanelLayout.setHorizontalGroup(
            jLeitarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLeitarPanelLayout.createSequentialGroup()
                .addContainerGap(293, Short.MAX_VALUE)
                .addGroup(jLeitarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLeitarPanelLayout.createSequentialGroup()
                        .addComponent(jWhen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToWhere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jFromWhere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLeitarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(searchButton)
                        .addComponent(jAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jLeitarPanelLayout.setVerticalGroup(
            jLeitarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLeitarPanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jLeitarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToWhere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jWhen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFromWhere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        jTableResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableResults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableResultsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableResults);

        jBacktoSearch.setText("Back to Search");

        javax.swing.GroupLayout jResultPanelLayout = new javax.swing.GroupLayout(jResultPanel);
        jResultPanel.setLayout(jResultPanelLayout);
        jResultPanelLayout.setHorizontalGroup(
            jResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jResultPanelLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(jResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBacktoSearch))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jResultPanelLayout.setVerticalGroup(
            jResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jResultPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBacktoSearch)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLeitarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jResultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLeitarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jResultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 504, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        //Let's get the values for the parameters
        String fromWhere = jFromWhere.getSelectedItem().toString();
        String toWhere = jToWhere.getSelectedItem().toString();
        int when =Integer.valueOf(jWhen.getText());
        int numberofPpl;
        
        
        //Check if numberofPpl was chosen, maybe just have a default?
        //Check if date is right?
        try{
        numberofPpl = Integer.valueOf(jAmount.getSelectedItem().toString());
        
        } catch (Exception e){
            System.out.println("Error: " + e.getMessage());  
            numberofPpl = 0;
        }
        
        
        //Next we start working with the information we received
        //We create a search 
        UpdateView(fromWhere, when, numberofPpl, toWhere);
        
        //We update the view
        
        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void jFromWhereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFromWhereActionPerformed
        
    }//GEN-LAST:event_jFromWhereActionPerformed

    private void jToWhereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToWhereActionPerformed
        
    }//GEN-LAST:event_jToWhereActionPerformed

    private void jWhenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWhenActionPerformed
        
    }//GEN-LAST:event_jWhenActionPerformed

    private void jLeitarPanelComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLeitarPanelComponentHidden
 
    }//GEN-LAST:event_jLeitarPanelComponentHidden

    private void jTableResultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableResultsMouseClicked
        evt.getSource();
        
    }//GEN-LAST:event_jTableResultsMouseClicked
    
    private void UpdateView(String toWhere, int date, int numbofPpl, String fromWhere){
        jTableResults.setModel(JoeTheTaskManager.manageSearch(toWhere, date, numbofPpl, fromWhere));
        jResultPanel.setVisible(true);
        jLeitarPanel.setVisible(false);
    }
    //private void sendumEfnid(int numberofPpl, String hvar, String toWhere, String when){
        //birtumEfnid(nyLeit);
   // }
    //private void birtumEfnid( ...){
   //     efnid.toString();
        
        
    //}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jAmount;
    private javax.swing.JButton jBacktoSearch;
    private javax.swing.JComboBox<String> jFromWhere;
    private javax.swing.JPanel jLeitarPanel;
    private javax.swing.JPanel jResultPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableResults;
    private javax.swing.JComboBox<String> jToWhere;
    private javax.swing.JTextField jWhen;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
